apiVersion: v1
kind: Pod
metadata:
  name: etl-pod
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: Default
  containers:
  - name: etl-pod
    image: brentgroves/etl-pod:6
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          cron -f 
    # command: ["/bin/sleep", "3650d"]
    imagePullPolicy: Always
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: db-user-pass
      optional: false # default setting; "mysecret" must exist    
    # imagePullPolicy: IfNotPresent
  restartPolicy: Always  

